version: '3.9'
services:
  web:
    image: nginx
    container_name: web_1
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST=homelab.localhost

networks:
  nginx-proxy:
    external: true
