version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx_proxy_client
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
      # 433 is the default SSL port, needed for https:// protocol.
      # - '433:433'
    depends_on:
      # make sure to append depends_on, services will be started in dependency order!
      - nginx_proxy
    # env_file:
    #   - ./common.env
    environment:
      # - ENV=development
      - APPLICATION_URL=http://homelab/nginx-proxy-client
      - VIRTUAL_HOST=homelab.local
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  nginx-proxy:
    # *** network is not created in this compose, so external: true ***!
    # TODO: network should be created inside proxy_nginx container, all others are dependent on the reverse-proxy!
    external: true
