version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx_web
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST=web1.localhost

networks:
  nginx-proxy:
    # *** network is not created in this compose, so external: true ***!
    # TODO: network should be created inside proxy_nginx container, all others are dependent on the reverse-proxy!
    external: true
