version: '3.9'
services:
  web:
    image: nginx
    container_name: web_test
    restart: unless-stopped
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST='homelab.web1'
    volumes:
      - './site_content:/usr/share/nginx/html'
networks:
  default:
    external:
      name: nginx-proxy
