version: '3.9'
services:
  webserver1:
    image: nginx
    container_name: webserver1
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: webserver1.local
  webserver2:
    image: nginx
    container_name: webserver2
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: webserver2.local

# *** network is not created in this compose, so external: true ***!
# TODO: network should be created inside proxy_nginx container, all others are dependent on the reverse-proxy!
networks:
  nginx-proxy:
    external: true
