version: '3.9'
services:
  web:
    image: nginx
    container_name: web_test
    restart: unless-stopped
    expose:
      - '80'
    # ports:
    # - '80:80'
    volumes:
      - './site_content:/usr/share/nginx/html'
