version: '3.9'
services:
  web:
    image: nginx
    container_name: web_test
    restart: unless-stopped
    networks:
      - nginx-proxy_default
    expose:
      - '80'
    # ports:
    # - '80:80'
    environment:
      - VIRTUAL_HOST='192.168.2.100/webtest'
    volumes:
      - './site_content:/usr/share/nginx/html'
