version: '3.9'
services:
  web:
    image: nginx
    container_name: web_test
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST='192.168.2.100'
    # volumes:
    #   - './site_content:/usr/share/nginx/html'

networks:
  nginx-proxy:
    external: true
